apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-ns
data:
  # Database configuration
  MYSQL_DATABASE: wp-db
  MYSQL_USER: wp_user
  
  # wordpress configuration
  WORDPRESS_DB_HOST: "mysql-svc"
  WORDPRESS_DB_USER: wp_user
  WORDPRESS_DB_NAME: wp-db

  # PMA configuration
  PMA_HOST: "mysql-svc"
  PMA_PORT: "3306"