apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql-db
  name: mysql-db
  namespace: wordpress-ns
spec:
  replicas: 1
  serviceName: "mysql-headless"
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        envFrom:
        - configMapRef:
            name: wordpress-config
        - secretRef:
            name: wordpress-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: pvc-mysql

